# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1377780429);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 184320);
user_pref("browser.migration.version", 13);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.slowStartup.averageTime", 5835);
user_pref("browser.slowStartup.samples", 1);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1377866828781");
user_pref("datareporting.policy.firstRunTime", "1377780428781");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.firstPaint", 5779);
user_pref("datareporting.sessions.current.main", 1042);
user_pref("datareporting.sessions.current.sessionRestored", 5820);
user_pref("datareporting.sessions.current.startTime", "1377780424073");
user_pref("datareporting.sessions.current.totalTime", 9);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"inline@webconverger.com\":{\"version\":\"1.0.2.4\",\"type\":\"extension\",\"descriptor\":\"/opt/firefox/browser/extensions/inline@webconverger.com\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "kiosk%40webconverger.com:46,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:20.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"inline@webconverger.com\":{\"descriptor\":\"/opt/firefox/browser/extensions/inline@webconverger.com\",\"mtime\":1377780245000,\"rdfTime\":1377780245000},\"kiosk@webconverger.com\":{\"descriptor\":\"/opt/firefox/browser/extensions/kiosk@webconverger.com\",\"mtime\":1377780423000,\"rdfTime\":1377780245000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/opt/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1377780245000,\"rdfTime\":1377780245000}}}]");
user_pref("extensions.lastAppVersion", "23.0");
user_pref("extensions.lastPlatformVersion", "23.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20130730113002");
user_pref("gecko.mstone", "23.0");
user_pref("intl.charsetmenu.browser.cache", "windows-1252");
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 6448);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1377780425);
user_pref("toolkit.telemetry.previousBuildID", "20130730113002");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1380372431);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
